# Hexo Configuration
## Docs: https://hexo.io/docs/configuration.html
## Source: https://github.com/hexojs/hexo/

# Site
title: 张学武(Shaw)
subtitle: Artificial Intelligence Innovation Laboratory
author: shaw 
language: 
timezone: 

# custom Site settings
# more detail check out docs
SEOTitle: 张学武(Shaw)的博客
header-img: http://o7bkkhiex.bkt.clouddn.com/lion-blur-bg.jpg
email: aiishaw@126.com
description: "张学武　在Github 上的个人博客"
keyword: 深度学习 博客 个人 张学武 Shaw# seo key words

# custom end

# URL
## If your site is put in a subdirectory, set url as 'http://yoursite.com/child' and root as '/child/'
url: http://blog.hosea.xyz
root: /
permalink: :year/:month/:day/:title/
permalink_defaults:

# SNS settings
# RSS:
weibo_username: 
zhihu_username: 
github_username: aiilab
twitter_username: 
facebook_username: 
linkedin_username: 

# Build settings
anchorjs: false                        # if you want to customize anchor. check out line:181 of `post.html`


# Disqus settings 
disqus_username:  

# Duoshuo settings
duoshuo_username:  
# Share component is depend on Comment so we can NOT use share only.
duoshuo_share: true                     # set to false if you want to use Comment without Sharing


# Analytics settings
# Baidu Analytics
ba_track_id: b2dec27247a6a21a0f13cd9e5c79ca8e
# Google Analytics
ga_track_id:             # Format: UA-xxxxxx-xx
ga_domain: 

# Sidebar settings
sidebar-about-description: AI R&D 
sidebar-avatar:  /about/shaw.jpg


# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value

# friends
friends:  [
    {
        title: "HoseaHsu",
        href: "http://hosea.xyz"
    },
    {
        title: "Hosea",
        href: "http://hosea.pw"
    }
]

# Directory
source_dir: source
public_dir: ../public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link: true # Open external links in new tab
filename_case: 0
render_drafts: false
post_asset_folder: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: false
  auto_detect: false
  tab_replace:

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss

# Pagination
## Set per_page to 0 to disable pagination
per_page: 8
pagination_dir: page

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: Anisina

# Deployment
## Docs: https://hexo.io/docs/deployment.html
deploy:
  type: git 
  repo: git@github.com:aiilab/blog.git 
  branch: gh-pages 


# img CDN path
cdn-url:  # 你的CDN地址

# Qiniu imageView2 API
# More info http://developer.qiniu.com/code/v6/api/kodo-api/image/imageview2.html
clip-content: "?imageView2/1/w/1400/h/400/interlace/1/q/90"
clip-avatar: "?imageView2/2/w/200/h/200/interlace/1/q/90"
clip-home-post-bg: "?imageView2/1/w/800/h/300/interlace/1/q/70"

# post default images
post-default-img: #博文默认的图片
post-default-img-mobile: #移动端显示的图片

# search api , set your custom key
swiftype_key: 

